#!/usr/bin/env bash
# Scaffold demo/ in the target project: directory layout, brief template, gitignore
# entries, and a copy of the bundled Remotion project.
#
# Idempotent — safe to re-run. Existing brief.md and storyboard.json are never touched.
# The studio project is refreshed only with --force-studio, so local customisation of the
# compositions survives (that is the documented escape hatch).
#
# usage: init-demo.sh [--project DIR] [--force-studio]
set -euo pipefail

PLUGIN_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PROJECT="$(pwd)"
FORCE_STUDIO=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project) PROJECT="$2"; shift 2 ;;
    --force-studio) FORCE_STUDIO=1; shift ;;
    *) echo "demo-video: unknown argument $1" >&2; exit 1 ;;
  esac
done

DEMO="$PROJECT/demo"
mkdir -p "$DEMO"/{capture,audio/music,prep,out,studio}

# ── Brief template ─────────────────────────────────────────────────────────────
if [[ ! -f "$DEMO/brief.md" ]]; then
  cat > "$DEMO/brief.md" <<'MD'
# Demo brief

Fill this in (or let Codex draft it from the codebase and confirm it) before any
storyboard work. Everything downstream — narration, pacing, which features make the cut —
is decided by these answers.

## Audience

Who watches this, and what decision are they making while watching?
<!-- e.g. "engineering leads evaluating whether to adopt this instead of X" -->

## Length

Target duration:
<!-- 60-120s is right for most product demos; over 3 min needs chapters -->

## The one thing

If a viewer remembers a single thing, what is it?

## Must show

- <!-- capability, and why it matters to the audience -->

## Do not show

- <!-- unfinished areas, fake data, anything embarrassing or sensitive -->

## Tone

<!-- e.g. "confident, concrete, no hype" -->

## Surfaces

- [ ] Web app — URL:
- [ ] Electron/desktop app — launch:
- [ ] CLI / code walkthrough

## Capture

Who drives the app, and what records it (see demo-capture):

- driver: mcp (web) / launch (Electron, the pipeline starts it) / attach (it runs on its own, CDP port: )
- recorder: playwright (headless web) / obs (a real window — text stays crisp)

## App state

How is demo-worthy data created? (seed script, fixture, demo account)

## Voice

Preferred narrator character, language, any pronunciation notes (product names!).

## Finish

- [ ] Remotion — rendered headlessly, re-renders when the app changes
- [ ] Final Cut Pro — exported as an FCP project, finished by hand with FCP titles
MD
  echo "  created demo/brief.md"
fi

# ── Remotion studio project ────────────────────────────────────────────────────
TEMPLATE="$PLUGIN_ROOT/assets/remotion-template"
if [[ ! -f "$DEMO/studio/package.json" || "$FORCE_STUDIO" -eq 1 ]]; then
  if [[ "$FORCE_STUDIO" -eq 1 && -f "$DEMO/studio/package.json" ]]; then
    echo "  refreshing demo/studio from the bundled template (--force-studio)"
    rm -rf "$DEMO/studio/src"
  fi
  mkdir -p "$DEMO/studio"
  cp -R "$TEMPLATE/." "$DEMO/studio/"
  echo "  installed Remotion project at demo/studio"
else
  echo "  demo/studio already exists — left alone (use --force-studio to overwrite)"
fi

# A default timeline so `npm start` in the studio works before anything is captured.
if [[ ! -f "$DEMO/timeline.json" ]]; then
  cp "$TEMPLATE/timeline.default.json" "$DEMO/timeline.json"
  echo "  seeded demo/timeline.json with a placeholder (reconcile overwrites it)"
fi

# ── gitignore ──────────────────────────────────────────────────────────────────
GITIGNORE="$PROJECT/.gitignore"
if ! grep -q '^demo/capture/' "$GITIGNORE" 2>/dev/null; then
  cat >> "$GITIGNORE" <<'IGN'

# demo-video-plugin — media is regenerable, the source of truth is storyboard.json
demo/capture/
demo/audio/
demo/out/
demo/studio/node_modules/
demo/timeline.json
IGN
  echo "  added demo media paths to .gitignore"
fi
# Isolated app state for capture (a throwaway database, a copy of the documents) is
# regenerated by demo/prep/ scripts and never committed.
if ! grep -q '^demo/prep/state/' "$GITIGNORE" 2>/dev/null; then
  printf 'demo/prep/state/\n' >> "$GITIGNORE"
  echo "  added demo/prep/state/ to .gitignore"
fi

cat <<TXT

demo-video: scaffolded $DEMO

  brief.md        ← fill in / confirm first
  storyboard.json ← written at the scripting stage (validated on every write)
  prep/           ← seed + determinism scripts
  capture/        ← clips, one per section (gitignored)
  audio/          ← narration, one per section (gitignored)
  timeline.json   ← generated by reconcile.mjs (gitignored)
  studio/         ← Remotion project, reads ../timeline.json
  out/            ← renders (gitignored)

Committed: brief.md, storyboard.json, prep/. Everything else rebuilds from those.
TXT
